### PR TITLE
NetworkImageLoadException (HTTP request failed, statusCode: 403, ...)

### LINKED ISSUE #6: NetworkImageLoadException (HTTP request failed, statusCode: 403, ...)
`lib/screens/detail_screen.dart` 과 `lib/widgets/webtoon_widget.dart` 파일안에 `Image.network` 를 사용하여 사진을 요청 시, 플렛폼 마다 오류가 발생합니다:

- Success: Web
- Fail: iOS, Android, macOS

그리고 아래와 같이 `Image.network` 의 `'headers'` property 에 `"User-Agent"` 추가 시, 플렛폼 마다 오류가 발생합니다:

```dart
Image.network(
  thumb,
  headers: const {
    "User-Agent":
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  },
)
```

- Success: iOS, Android, macOS
- Fail: Web

결론은 단말 유형에 따른 제어가 필요합니다.

### PR DESCRIPTION
**Pull request by portal2312**
Fixes #6

### CODE REVIEW

File: lib/screens/detail_screen.dart [hunk 1]
```diff
@@ -70,13 +71,13 @@ class _DetailScreenState extends State<DetailScreen> {
...
                       ),
                       width: 250,
-                      // BUG: #6 NetworkImageLoadException (HTTP request failed, statusCode: 403, ...)
                       child: Image.network(
                         widget.thumb,
-                        headers: const {
-                          "User-Agent":
-                              "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
-                        },
+                        headers: kIsWeb
```
Comment (portal2312) [inline lib/screens/detail_screen.dart:76]: Awesome

File: lib/widgets/webtoon_widget.dart [hunk 2]
```diff
@@ -33,13 +34,13 @@ class Webtoon extends StatelessWidget {
...
               ),
               width: 250,
-              // BUG: #6 NetworkImageLoadException (HTTP request failed, statusCode: 403, ...)
               child: Image.network(
                 thumb,
-                headers: const {
-                  "User-Agent":
-                      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
-                },
+                headers: kIsWeb
```
Comment (portal2312) [inline lib/widgets/webtoon_widget.dart:39]: Awesome:

```suggestion
                headers: kIsWeb ? null : const { 'Referer': 'https://comic.naver.com', },
```

**Review by portal2312 — COMMENTED** [review]
Awesome

**Comment by portal2312** [comment]
https://azuredevopslabs.com/labs/azuredevops/githubpullrequests/
